category: generic
site: computer-database.gatling.io
successful_runs: Click 'Add a new computer'. Name 'TestComp_Unique'. Introduced '2023-01-01'.
  Discontinued '2024-01-01'. Company 'Apple Inc.'. Create. Filter by 'TestComp_Unique'.
  Click result. Edit name to 'TestComp_Edited'. Save. Filter 'TestComp_Edited'. Click
  result. Delete.
total_trace_steps: 1
