category: enterprise_hr
site: opensource-demo.orangehrmlive.com
successful_runs: 'MISSION: 1. Login. 2. Navigate to PIM module and Add a new employee
  (FirstNameTest LastNameTest). 3. Click SAVE to finish onboarding. 4. Navigate to
  Admin module -> User Management -> Users. 5. Create a System User for the newly
  created employee. THE MISSION IS ONLY SUCCESSFUL IF ALL STEPS ARE COMPLETED.'
total_trace_steps: 15
