category: saas
site: opensource-demo.orangehrmlive.com
successful_runs: Verify login page elements, check forgot password link, and view
  social media icons.
<<<<<<< Updated upstream
total_trace_steps: 9
=======
total_trace_steps: 7
>>>>>>> Stashed changes
