category: hr
site: opensource-demo.orangehrmlive.com
successful_runs: Login 'Admin'/'admin123'. Click Admin. Click Add (User). Role 'ESS'.
  Name 'Ranga Akunuri'. Status 'Enabled'. User 'testuser_8315'. Pass 'Password123!'.
  Save. Click PIM. Add Employee. First 'John', Last 'Doe'. Save. Click Directory.
  Search 'John Doe'. Logout.
total_trace_steps: 7
