category: entertainment
site: www.disneyplus.com
successful_runs: Navigate to Disney+ homepage. Verify the hero headline contains 'The
  best stories in one place'. Find and click the 'Sign Up Now' button.
total_trace_steps: 15
