category: general
site: www.dyson.in
successful_runs: '1. Handle Popup: Close popup[Optional step]. 2. Search: Search for
  ''Dyson V15 Detect''. 3. Verify: Verify ''Add to Cart'' button.'
total_trace_steps: 6
