category: e_commerce
site: www.dyson.in
successful_runs: '1. Handle Popup: Close ''Subscribe'' popup[Optional step]. 2. Search:
  Search for ''Dyson V15 Detect'' and click the first product result[Keep trying and
  Self learning]. 3. PDP Verification: Verify ''Add to Cart'' button is visible.'
total_trace_steps: 10
