category: general
site: www.dyson.in
successful_runs: '1. Handle Popup: Close ''Subscribe'' popup[Optional step]. 2. Search:
  click on Search Products and parts and then enter ''Dyson V15 Detect''. 3. Verification:
  Verify ''Add to Cart'' button.'
total_trace_steps: 3
