category: ecommerce
site: www.hilton.com
successful_runs: Navigate to Hilton homepage. Verify the hero headline contains 'Expect
  better. Expect Hilton.'. Find and click the 'Book a Stay' button.
total_trace_steps: 15
