category: saas
site: www.automatur.com
successful_runs: 1. Click on Home, Price, Features one by one and validate page content.
  2. Verify visibility of all primary CTA buttons and navigational links even if not
  explicitly mentioned in the core flow. 3. Click on 'Have a Question?', submit the
  form with randomized data, and validate submission. 4. Click on 'Sign Up' and fill
  in dynamic details (name, email, password) to register.
total_trace_steps: 7
