category: generic
site: the-internet.herokuapp.com
successful_runs: Click 'Form Authentication'. Login 'tomsmith'/'SuperSecretPassword!'.
  Logout. Back. Click 'Checkboxes'. Check both. Back. Click 'Dropdown'. Select Option
  2. Back. Click 'Dynamic Controls'. Click Remove. Wait for 'It's gone!'. Click Add.
  Wait for 'It's back!'. Back. Click 'Inputs'. Type number. Back.
total_trace_steps: 7
