category: isp_telecom
site: my.astound.com
successful_runs: 'Smoke Suite: Login (User: vishvas.mca@gmail.com, Pass: Myaccount@123),
  Explore Billing, Check Payments, Enable SMS Notifications, Logout'
total_trace_steps: 2
