category: banking
site: parabank.parasoft.com
successful_runs: 'Full Regression: Register a new user with unique details, Open a
  new Checking Account, Transfer  from the new account to the old one, Pay a Bill
  of  to ''Electric Company'', and finally Logout.'
total_trace_steps: 42
