category: banking
site: parabank.parasoft.com
successful_runs: Register new user 2636. Open New Account (Savings). Click Accounts
  Overview. Click the new account. Click Transfer Funds. Transfer $50 to new account.
  Click Bill Pay. Pay 'Electric Co' $100. Find Transactions by Amount $50. Update
  Contact Info 'Phone' to '555-0000'. Logout.
total_trace_steps: 3
