category: banking
site: parabank.parasoft.com
successful_runs: Verify login page, check find transactions link, and navigate to
  about us.
<<<<<<< Updated upstream
total_trace_steps: 3
=======
total_trace_steps: 15
>>>>>>> Stashed changes
