category: general
site: katalon.com
successful_runs: '1. Go to https://katalon.com/. 2. Click ''Products'' menu, visit
  sub-items. 3. Click ''Solutions'' menu, visit sub-items. 4. On each visited page,
  validate all visible links (check for 404s). 5. Navigate to ''Contact Us'' page.
  6. Fill details (Name: Test User, Email: test@example.com).'
total_trace_steps: 3
