category: ecommerce
site: automationexercise.com
successful_runs: Navigate to Products, search for 'Dress', add to cart, and go to
  checkout.
<<<<<<< Updated upstream
total_trace_steps: 7
=======
total_trace_steps: 5
>>>>>>> Stashed changes
