category: e_commerce
site: automationexercise.com
successful_runs: '1. Navigation: Click ''Products'' (handle potential full-screen
  ads). 2. Search: Search for ''Blue Cotton'' and click ''View Product'' on the first
  result. 3. Action: Add to cart. 4. Verify: Go to ''View Cart'' and ensure the product
  is listed.'
total_trace_steps: 7
