category: ecommerce
site: automationexercise.com
successful_runs: Click Products. Search 'Dress'. Add first result. Continue Shopping.
  Add second result. Click Cart. Click Signup/Login. Signup 'NewUser' (1040 email).
  Fill details 'Mr', 'Pass123', '1', 'Jan', '2000', 'First', 'Last', 'Company', 'Address',
  'State', 'City', '10001', '123123123'. Create Account. Continue. Cart. Proceed to
  Checkout. Place Order. Card 'Name', '1234567812345678', '123', '01', '2030'. Pay.
  Delete Account.
total_trace_steps: 3
