category: ecommerce
site: automationexercise.com
successful_runs: '1. Navigate to ''Test Cases''. 2. Return to ''Products''. 3. Click
  ''Women'' category > ''Dress'' subcategory. 4. Add the first dress to cart & continue.
  5. Search for ''Green Side Striped T-shirt''. 6. Add it to cart & continue. 7. Go
  to Cart. 8. Click ''X'' button to remove the first item. 9. Proceed to Checkout.
  10. Register with ''Kitchen Sink'' and ''v11_final_test_@gmail.com''. 11. Fill signup
  (Pass: 12345, FName: Kitchen, LName: Sink, Address: 11 AI Road, State: NY, City:
  NY, Zip: 10001, Mobile: 999111222). 12. Create Account & Continue. 13. Verify Logged
  in. 14. Add another random product from ''Products'' to ensure cart is not empty.
  15. Go to Cart & Checkout. 16. Verify Address & Order. 17. Place Order. 18. Pay
  (Card: Sink, No: 1, CVC: 111, Exp: 01/2025). 19. Confirm Order. 20. Click ''Download
  Invoice''. 21. Delete Account. 22. Verify ''Account Deleted'' and Continue.'
total_trace_steps: 8
