category: general_web
site: automationexercise.com
successful_runs: Click on 'Contact Us' button. Fill Name='Test User', Email='test@example.com',
  Subject='Support', Message='This is a test message'. Click 'Submit' button and verify
  'Success' message if visible.
total_trace_steps: 4
