category: ecommerce
site: www.saucedemo.com
successful_runs: Login with standard_user and secret_sauce. Add the 'Sauce Labs Backpack'
  to the cart. Verify the cart badge shows '1' and click on the cart icon.
total_trace_steps: 5
