category: ecommerce
site: www.saucedemo.com
successful_runs: Login 'standard_user'/'secret_sauce'. Sort Z-A. Add 'Test.allTheThings()
  T-Shirt'. Go to item details 'Sauce Labs Onesie'. go back. Add 'Sauce Labs Bike
  Light'. Go to Cart. Checkout. Info 'Jane' 'Doe' '12345'. Finish. Back Home. Logout.
total_trace_steps: 5
