category: e_commerce
site: www.saucedemo.com
successful_runs: '1. Login: standard_user / secret_sauce. 2. Action: Add three items
  (Backpack, Bike Light, Bolt T-Shirt) to the cart. 3. Checkout: Go to the cart, click
  ''Checkout'', fill in ''First'', ''Last'', and ''11111'' zip code. 4. Finalize:
  Click ''Continue'' and then ''Finish''. 5. Verify: Assert that ''Thank you for your
  order!'' is displayed.'
total_trace_steps: 5
