category: ecommerce
site: www.saucedemo.com
successful_runs: Login with username 'standard_user' and password 'secret_sauce'.
  Then sort items by 'Price (low to high)'. Add the first item to the cart. Navigate
  to cart. Click Checkout.
total_trace_steps: 5
