category: general
site: www.saucedemo.com
successful_runs: Login with username 'standard_user' and password 'secret_sauce',
  add Sauce Labs Backpack to cart, proceed to checkout, enter first name 'John', last
  name 'Doe', zip '12345', and finish.
total_trace_steps: 4
