category: ecommerce
site: www.walmart.com
successful_runs: Navigate to Walmart homepage. Verify the hero headline contains 'Save
  money. Live better.'. Find and click the 'Shop Now' button.
total_trace_steps: 15
