category: ecommerce
site: www.target.com
successful_runs: Navigate to Target homepage. Verify the hero headline contains 'Expect
  more. Pay less.'. Find and click the 'Shop Now' button.
total_trace_steps: 15
