category: documentation
site: playwright.dev
successful_runs: Navigate to Playwright.dev. Verify the main heading 'Playwright enables
  reliable end-to-end testing' is visible. Click on 'Get Started' button.
total_trace_steps: 1
