category: general
site: www.atlassian.com
successful_runs: Navigate to Atlassian Jira homepage. Verify the hero headline contains
  'Plan, track, and release great software'. Find and click the 'Try it free' button.
total_trace_steps: 15
