category: generic
site: ultimateqa.com
successful_runs: Click 'Big page with many elements'. Fill Name. Fill Email. Click
  Button. Back. Click 'Fill out forms'. Fill Name. Fill Message. Submit. Back. Click
  'Fake Landing Page'. Click 'View Courses'. Search 'Python'. Verify results.
total_trace_steps: 2
