category: ecommerce
site: magento.softwaretestingboard.com
successful_runs: 'Comprehensive E2E Flow: 1. Search for ''Jacket''. 2. Click on the
  first product ''Olivia 1/4 Zip Light Jacket''. 3. Select Size ''M''. 4. Select Color
  ''Purple''. 5. Add to Cart. 6. Wait for success message. 7. Click on the ''Sale''
  menu link. 8. Click on ''Tees'' in the left sidebar. 9. Click on ''Desiree Fitness
  Tee''. 10. Select Size ''L''. 11. Select Color ''Black''. 12. Add to Cart. 13. Click
  on the Cart icon in header. 14. Click ''View and Edit Cart''. 15. Update ''Desiree
  Fitness Tee'' quantity to 2. 16. Click ''Update Shopping Cart''. 17. Verify usage
  of coupons is available. 18. Proceed to Checkout. 19. Enter email ''test_user_99@example.com''.
  20. Fill First Name ''Test'', Last Name ''User''. 21. Fill Street Address ''123
  Test St''. 22. Fill City ''New York''. 23. Select State ''New York''. 24. Fill Zip
  ''10001''. 25. Fill Phone ''1234567890''. 26. Select Shipping Method ''Table Rate''.
  27. Click Next. 28. Verify ''Payment Method'' step is visible. 29. Click Place Order.
  30. Verify Order Confirmation number is visible.'
total_trace_steps: 1
