category: ecommerce
site: magento.softwaretestingboard.com
successful_runs: Search 'Jacket'. Click 'Olivia 1/4 Zip'. Size 'M', Color 'Purple'.
  Add to Cart. Click 'Sale'. Click 'Tees'. Click 'Desiree Fitness Tee'. Size 'L',
  Color 'Black'. Add to Cart. Edit Cart. Update 'Desiree' qty to 2. Update Cart. Checkout
  as guest 'test@example.com', 'Test' 'User', '123 St', 'New York', 'NY', '10001',
  '1234567890'. Shipping 'Table Rate'. Payment. Place Order.
total_trace_steps: 3
