category: general_web
site: vedcdnlb.com
successful_runs: Launch website, find Login, Signup/GetStarted, Try for Free etc any
  5 buttons and 2 links, 2 menu bar with out clicking any one of them
total_trace_steps: 2
