category: ecommerce
site: rahulshettyacademy.com
successful_runs: Register 3531. Login. Filter 'zara coat 3'. Add to Cart. Click Cart.
  Checkout. Select Country 'India'. Place Order. Click Orders. Click View on first
  order. Verify summary. Sign Out.
total_trace_steps: 4
