category: entertainment
site: www.tripadvisor.com
successful_runs: Navigate to TripAdvisor homepage. Verify the hero headline contains
  'Know better. Book better. Go better.'. Find and click the 'Start Planning' button.
total_trace_steps: 0
