category: saas
site: testgrid.io
successful_runs: Navigate to TestGrid homepage. Verify the hero headline contains
  'UNIFIED Test Infrastructure & Software Testing Platform'. Find and click the 'Book
  Demo' button.
total_trace_steps: 15
