category: e_commerce
site: www.demoblaze.com
successful_runs: '1. Search/Filter: Click ''Laptops'' category. 2. Selection: Click
  on ''Sony vaio i5''. 3. Action: Click ''Add to cart'' and accept the alert. 4. Checkout:
  Go to ''Cart'', click ''Place Order'', fill ''Name'' and ''Credit card'' in the
  modal, and click ''Purchase''.'
total_trace_steps: 9
