category: ecommerce
site: www.demoblaze.com
successful_runs: Sign up 7683. Login. Click 'Laptops'. Click 'Sony vaio i5'. Add to
  cart. Home. Click 'Monitors'. Click 'Apple monitor 24'. Add to cart. Cart. Delete
  'Sony vaio i5'. Place Order. Name 'Test', Card '1234'. Purchase. Log out.
total_trace_steps: 7
