category: education
site: www.careerraah.com
successful_runs: Navigate to CareerRaah homepage. Verify the main heading is visible.
  Click on 'Career Counseling' or 'Explore Programs' if available.
total_trace_steps: 1
